### ISSUE TITLE
"Staff computing & networking" needed? 

### ISSUE THREAD

**Issue by akadams** [trustedci/OSCRP#10]
The risk for an institutions staff computing and networking should be absorbed by that institution, thus, it's unclear to me that  it should be part of a project's threat profile ... But as always, I could be wrong.  :-)

**Comment by dopheide-esnet** [comment]
This may be a special case... maybe there is no avenue for attack, but we think it's a valuable concern.

**Comment by akadams** [comment]
Ended up leaving it in, as it was an asset in one of the bad-times scenario examples.
