### ISSUE TITLE
"Network-connected building control systems" needed?

### ISSUE THREAD

**Issue by akadams** [trustedci/OSCRP#12]
First, with _systems_ in its name, it sounds like it should be under _Systems_, not _Instruments_.  That said, I'm not sure how this profile would differ from looking at both "Sensor Instruments" & "Networks"?  Admittedly, we may not yet have a "Sensor Instruments" diagram, but I suspect we'll cover AoAs & concerns in more detail keeping sensor hardware separate from networking.

**Comment by dopheide-esnet** [comment]
Perhaps just add "network-connected building control systems" as an example inside the Facilities Asset and that should be good.
