### ISSUE TITLE
Resource/Financial loss

### ISSUE THREAD

**Issue by akadams** [trustedci/OSCRP#15]
Where should financial/resource consequences be represented?  In the, e.g., hardware asset?  As a new link in the data assets?

**Comment by von** [comment]
E.g. Unauthorized use of commercial web service. Or DDOS of your service.

Consequence is you have fewer resources to do other stuff.

**Comment by von** [comment]
Ransomware?

**Comment by dopheide-esnet** [comment]
Financial loss is easily understood by scientists, perhaps a small paragraph describing consequences that weren't clear from existing incident examples.  --Karen

**Comment by akadams** [comment]
Sounds like we think it should be an asset, _and_ defined in the Asset definition.

**Comment by von** [comment]
I think specifically in "Intangible and Human Assets"
