### ISSUE TITLE
Account for models/algorithms in assets

### ISSUE THREAD

**Issue by akadams** [trustedci/OSCRP#16]
We need an asset (either by itself or incorporated into another data asset) that describes protocols/models/algorithms.

**Comment by akadams** [comment]
And workflow!

**Comment by thanne23** [comment]
Another good word for this category might be Karen's "workflow" term. (http://trustedci.github.io/OSCTP/assets/Workflow.html)

On Thu, Sep 29, 2016 at 12:33:04PM -0700, Andrew wrote:

> We need an asset (either by itself or incorporated into another data asset)
> that describes protocols/models/algorithms.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.*

## 

RuthAnne Bevier
Chief Information Security Officer
California Institute of Technology
ruthanne@caltech.edu
626-395-2671

**Comment by von** [comment]
Or http://trustedci.github.io/OSCTP/assets/Internal-software.html ?

**Comment by akadams** [comment]
There needs to be (at least) a reference in software.

**Comment by akadams** [comment]
Expand definition within the two software assets to including models/algo/processing code/workbooks.
