### ISSUE TITLE
Consistent capitalization of terms

### ISSUE THREAD

**Issue by kstocks** [trustedci/OSCRP#21]
Throughout the document, defined terms like Concern, Asset, Avenues of Attack, Open Science etc. are sometimes capitalized in the text, and sometimes not. It could go either way (I suggest not capitalized) but should be consistent.

**Comment by von** [comment]
I agree consistently is paramount. I'd come down slightly in favor of capitalization to make it clear we're using them with a specific meaning, but I'm not going to lose sleep over it.

**Comment by kstocks** [comment]
OK, I'm standardizing so that defined terms are capitalized, but not in quotes. Done for: Open Science. Rest to follow.

**Comment by kstocks** [comment]
OK, all special, defined terms should now be consistently capitalized. I "downgraded" a couple that I thought were being used in close to the normal english meaning: project mission, controls, exposure. I used lowercase for these terms throughout.
