### ISSUE TITLE
Number or title security incidents?

### ISSUE THREAD

**Issue by kstocks** [trustedci/OSCRP#24]
Consider whether the list of real security incidents should be either numbered, or have a brief bold title...they run together a bit visually.

**Comment by akadams** [comment]
I think this is/was already stated as an issue ... So, yes, I agree!

**Comment by von** [comment]
You are talking about the [examples](http://trustedci.github.io/OSCTP/OSCRP.html#examples-of-computer-security-incidents-affecting-research)?

If we number sections (see #31) I think this will accomplish this.

**Comment by kstocks** [comment]
I added some numbering. Because the main sections are numbered, I didn't want to just do integers, so I did "5-1" "5-2" etc. Not sure if that looks right...but am going to call this done.
