### ISSUE TITLE
Reword on last step in how to use

### ISSUE THREAD

**Issue by kstocks** [trustedci/OSCRP#26]
Line 171. Suggest replacing:

> Incorporate an annual refresh of this process into the project's activity cycle. Specifically considering if a project's assets have change, or the potential impact of the risks to the project has changed in such a way the project's risk profile may have changed.

With:

> Repeat this assessment annually, or more frequently if the project’s assets or risks have changed.

Trying to keep it short and simple...

**Comment by von** [comment]
+1

**Comment by kstocks** [comment]
Change made.
