### ISSUE TITLE
Move Definition of Terms

### ISSUE THREAD

**Issue by kstocks** [trustedci/OSCRP#27]
I think the document would read more smoothly if the section on how to use this document flowed directly into the usage example. This leaves the question of where to put the Definition of Terms...and I'm not sure the best answer. It could go before How To, or after the Usage Example, or in an appendix.  Or we could just define terms as we use them (which we have done with a few, like Open Science). I lean towards that approach, personally.

**Comment by von** [comment]
Let's try to spread the definitions throughout the document on first use instead of having a dedicated section.

**Comment by kstocks** [comment]
I removed the Project Mission definition - we are using it in its common language meaning. I also changed it to lower case in the text.

**Comment by kstocks** [comment]
All terms have now been defined in the text at first use. This has made the "overview and goals" section a bit definition-dense. The section definition terms has been deleted.
