### ISSUE TITLE
Line 60 grammar

### ISSUE THREAD

**Issue by kstocks** [trustedci/OSCRP#28]
Re: Line 60:

> The primary audience of this document is principal investigators of open science projects  involving computing infrastructure of any type (computing, networking, sensors, control systems, etc.…), as well...

The parenthetical list hit me as awkward, because it contained different kinds of items.  Sensors are a straight noun. Computing seems circular with "computing infrastructure of any type" (computing infrastructure of the computing type?). And networking is a ....what...gerund? Or acting as an adverb implicitly modifying "computing infrastructure"??? Dunno, grammar is not my strong suit, but I had trouble with the list in parenthesis and didn't see how to correctly it cleanly.

**Comment by von** [comment]
How about the following?

> The primary audience of this document is principal investigators (PIs) and information technology (IT) professionals involved in “open science” projects that rely on computing infrastructure (defined broadly: computers, networking, sensors, control systems, etc.)

**Comment by kstocks** [comment]
swapped in von's wording
