### ISSUE TITLE
Numbers in Table of Contents are not in text

### ISSUE THREAD

**Issue by pascal-meunier** [trustedci/OSCRP#31]
Items in the Table of Contents are numbered, but there are no numbers in the text to match.

**Comment by von** [comment]
The table of contents is an markdown numbers list. I believe we'd have to either manually number the sections or [use an additional program](http://stackoverflow.com/questions/19999696/are-numbered-headings-in-markdown-rdiscount-possible). I suggest we wait to manually number the sections until we're more confident they are finalized (e.g. #27 may cause us to renumber them).

**Comment by kstocks** [comment]
Done
