### ISSUE TITLE
Some links in editable version return 404

### ISSUE THREAD

**Issue by von** [trustedci/OSCRP#32]
E.g. Software assets

**Comment by dopheide-esnet** [comment]
Some of this is discussed here:
https://github.com/gitlabhq/gitlabhq/issues/3556

**Comment by von** [comment]
E.g. https://github.com/trustedci/OSCTP/blob/master/OSCRP.md link to https://github.com/trustedci/OSCTP/blob/master/assets/Third-party-software.html

**Comment by von** [comment]
I believe the problem is the file extension: ".md" vs ".html".

**Comment by peisert** [comment]
Yes -- GitHub wants .md and Jekyll wants .html

I wonder if we should change the naming from files to directories so that each scheme can just choose its preference.  E.g. this:

https://github.com/trustedci/OSCTP/blob/master/assets/Documentation.html

to this:

https://github.com/trustedci/OSCTP/blob/master/assets/Documentation/

**Comment by von** [comment]
I believe this was fixed with 24ab3b2151aa8afe9143006fe3a112761fec2e3e

**Comment by von** [comment]
The link in index.md to OSCRP.html returns 404. I think we need to move OSCRP.md under OSCRP/

**Comment by dopheide-esnet** [comment]
I believe OSCRP.md may then need to be renamed readme.md and it's permalink
edited.

**Comment by peisert** [comment]
Sounds good

**Comment by peisert** [comment]
Just to be really clear on this, we are renaming OSCRP.md to readme.md, but we're not replacing the existing readme.md, but putting this new readme.md inside a new directory called OSCRP, so that we can keep the existing landing page?

**Comment by akadams** [comment]
That's my understanding (assuming I parsed both Dop's and Von's comments
correctly).

Andrew

**Comment by akadams** [comment]
I believe we've addressed this, closing.
