### ISSUE TITLE
relational and other database engines 

### ISSUE THREAD

**Issue by dpetravick** [trustedci/OSCRP#43]
Do these need to be considered, as they are different than file stores, as  relational (or similar active technologies) can be attacked and used to alter data, or attack the system hosting the database engine, if there is a way to exec() code?

**Comment by peisert** [comment]
While relational databases are different than filesystems, I am not sure that Concerns, Consequences, or Avenues of Attack are substantially different than that of the file-store or back-end assets.  Is there something in one of those that isn't covered already?

**Comment by akadams** [comment]
+1 to Sean.  Where/how the data is stored is secondary to its content.  If the RDB itself is primary, then that's covered under applications.  Closing.
