### ISSUE TITLE
Add request for acknowledgement

### ISSUE THREAD

**Issue by von** [trustedci/OSCRP#48]
It would be useful for CTSC's reporting to NSF to know if people use the OSCRP and find it useful. I propose to add the following text under Section 3 ("Who This Document is Intended For"):

> If you utilize this document and find it useful, your acknowledgement of that (and other feedback) is requested by sending an email to info@trustedci.org

**Comment by akadams** [comment]
+1.  Although I could see us softening *requested* to, e.g., *would be appreciated* or *politely requested*?

(In any event, I'll add what Von has verbatim unless someone strongly objects by COB today.)
