### ISSUE TITLE
Provide more detailed instructions and/or HTML version to lower barriers to contribution

### ISSUE THREAD

**Issue by usethedata** [trustedci/OSCRP#49]
Reading the information on the CTSC site and here, I have some idea about what I'd have to go through to get a version of the information where I could make some contributions, but it's going to take some doing.  I've presumably got to get a Jekyll installation working (I don't have one), though I can get some portion of the way there reading the raw markdown files and/or using something like Marked to read through it.  But my cyber folks and most of the researchers who I'd want to work with to get their input are going to be completely clueless.  I'm going to have to do something like build an HTML version that I can show them and then integrate their input via issues and/or pull requests.  What can be done to lower the barriers to contribution?

**Comment by von** [comment]
Bruce - thanks for asking. Two things that perhaps are not obvious:

First, GitHub renders the guide automatically and you can view it at http://trustedci.github.io/OSCRP/OSCRP.html

Second,  I just added some details on a workflow to propose changes that is in-browser and requires no additional software: http://trustedci.github.io/OSCRP/OSCRP.html#contributing-to-this-document

Please let me know if those details help.

**Comment by akadams** [comment]
The *improvements* to the "Contributing" section are excellent, Von.  Closing this.
