### ISSUE TITLE
Adding recommended Citation

### ISSUE THREAD

**Issue by kstocks** [trustedci/OSCRP#55]
Could we add a recommended citation format for the document, perhaps in the Authors section? I'm citing it in a proposal, and I don't myself know how to create a citation from the 3 sets of contributors (Leads, core members, contributing members). Thanks.

**Comment by von** [comment]
How about:

> Peisert, Sean, Von Welch, Andrew Adams, RuthAnne Bevier,  Michael Dopheide, Rich LeDuc, Pascal Meunier, Steve Schwab, and Karen Stocks. 2017. Open Science Cyber Risk Profile (OSCRP). Available from:  http://trustedci.github.io/OSCRP/

**Comment by von** [comment]
BTW, I'm also thinking about taking a snapshot of the document as  a PDF and publishing that with a DOI. Let me know if that would be more useful.

**Comment by peisert** [comment]
I like the idea of a DOI.  We can do that with GitHub here:

https://guides.github.com/activities/citable-code/

**Comment by akadams** [comment]
Looks like I don't have authority to authorize Zenodo to create the DOI; can someone (Sean? Von?) if they get the request to authorize Zenodo, go ahead and do that.  Thanks.

**Comment by kstocks** [comment]
Thanks, Von! And I like the idea of a DOI as well.

I appreciate the speedy service!

-Karen


<><><><><><><><><><><><><><><><>
Karen Stocks, PhD
Director, Geological Data Center
Scripps Institution of Oceanography
+1 858-534-1898
kstocks@ucsd.edu

**Comment by peisert** [comment]
When I look at the WebHook interface in GitHub, it says "Access request pending" for Zenodo.  I'm an admin of the repository, but not the owner... I think Von may need to approve this.

**Comment by von** [comment]
I've approved the Zenodo access.

**Comment by peisert** [comment]
Here's the DOI: 10.5281/zenodo.345619


More info on how to create a badger with this DOI below:





DOI Badge

This badge points to the latest released version of your repository. If you want a DOI badge for a specific release, please follow the DOI link for one of the specific releases and grab badge from the archived record.

Markdown

[![DOI](https://zenodo.org/badge/51522464.svg)](https://zenodo.org/badge/latestdoi/51522464)

reStructedText

.. image:: https://zenodo.org/badge/51522464.svg
   :target: https://zenodo.org/badge/latestdoi/51522464


HTML

<a href="https://zenodo.org/badge/latestdoi/51522464"><img src="https://zenodo.org/badge/51522464.svg" alt="DOI"></a>

Image URL

https://zenodo.org/badge/51522464.svg

Target URL

https://zenodo.org/badge/latestdoi/51522464

**Comment by von** [comment]
Cool. 
It looks like we can use the following URL to link to a rendered markdown of a specific release. It doesn't render quiet as nicely as the normal rendering, but it's very readable. (Kudos to http://stackoverflow.com/a/19768224/197789)

> https://github.com/trustedci/OSCRP/blob/v.1.0/OSCRP.md

The zenodo target URL takes one to raw source, which while good from archival standpoint, I suspect won't be what most people want.

And I don't know if this is useful, but I tagged the V.1.0 release with the DOI, so we can have URLs that use the DOI, e.g.:
> https://github.com/trustedci/OSCRP/blob/10.5281%2Fzenodo.345619/OSCRP.md

**Comment by peisert** [comment]
Perfect -- thanks for figuring all that out, Von!

**Comment by peisert** [comment]
P.S. No reason not to also upload to our institutional repositories with a pointer to this DOI, too.

**Comment by akadams** [comment]
The subheading on the Zenodo DOI reads: "Von Welch; Sean Peisert; Andrew; kstocks; dopheide-esnet; Susan Sons; thanne23; Warren Raquel; Von's Forks".  I'm not sure where it's pulling those names/first names/e-mails in from ...

**Comment by akadams** [comment]
And those are how the names are showing up in the BibTeX.

**Comment by akadams** [comment]
Hmm, it also looks like Zenodo is only allowing one admin to generate the DOIs.  That is, I can't *enable* the on/off switch for OSCRP in Zenodo.

**Comment by akadams** [comment]
Ahh, not surprisingly, Zenodo is using the name field from our GitHub profiles.  Hence, we need to get Karen, Dop, etc. to update their profile names in GitHub (unless there's someway to override this in Zenodo's DOI creation?).  Not sure who "Von's Fork" is ...

**Comment by peisert** [comment]
Alternatively, we could delete Zenodo and get a DOI a different way. :-)  Thoughts?

**Comment by thanne23** [comment]
Done for thanne23.

On Mon, Mar 06, 2017 at 09:46:27AM -0800, Andrew K. Adams wrote:
> Ahh, not surprisingly, Zenodo is using the name field from our GitHub profiles.
> Hence, we need to get Karen, Dop, etc. to update their profile names in GitHub
> (unless there's someway to override this in Zenodo's DOI creation?). Not sure
> who "Von's Fork" is ...
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.*
> 

-- 
RuthAnne Bevier
Chief Information Security Officer
California Institute of Technology
ruthanne@caltech.edu
626-395-2671

**Comment by von** [comment]
Von's Fork is a purely administrative account I use. Ideally it would not appear in the list of authors.

**Comment by peisert** [comment]
So, deleting the Zenodo DOI and submitting a DOI request through IU may make more sense?

**Comment by kstocks** [comment]
Just updated my name in my GitHub profile, FWIW.

-Karen


<><><><><><><><><><><><><><><><>
Karen Stocks, PhD
Director, Geological Data Center
Scripps Institution of Oceanography
+1 858-534-1898
kstocks@ucsd.edu

**Comment by von** [comment]
My take is that Zenodo is good for a snapshot of the OSCRP source, which isn't surprising given its focus on software, but isn't really want people expect as a DOI for a document.

So I propose we take a snapshot of the document as a PDF and put it into IU's ScholarWorks system, e.g. like my team did for the slides from our webinar: http://hdl.handle.net/2022/21235

For the record, Figshare is also a viable option if someone wants to do this without the need to be at IU, e.g. https://dx.doi.org/10.6084/m9.figshare.4584256

**Comment by peisert** [comment]
I'm fine with either IU or arXiv, and defer to Von. I'm also happy to generate the PDF separately if Zenodo is producing authorship weirdness. 

 Can we delete the existing DOI?

**Comment by von** [comment]
Doing a quick test, I can print http://trustedci.github.io/OSCRP/OSCRP.html to a PDF and it looks pretty good: [Open Science Cyber Risk Profile.pdf](https://github.com/trustedci/OSCRP/files/825672/Open.Science.Cyber.Risk.Profile.pdf)

I will go ahead and start the process of getting this into IU Scholarworks, namely (documenting this in case I or someone has to do it again):

1. Create an placeholder entry in Scholarworks and get a permanent handle.
2. Add the agreed suggested reference, including the handle: "Peisert, Sean, Von Welch, Andrew Adams, RuthAnne Bevier, Michael Dopheide, Rich LeDuc, Pascal Meunier, Steve Schwab, and Karen Stocks. 2017. Open Science Cyber Risk Profile (OSCRP). <handle>"
3. Also add some text, intended for the PDF, on where to find the latest version of the document, i.e. http://trustedci.github.io/OSCRP/OSCRP.html
4. Add a v.1.0 version label to the document for the PDF.
5. Move the current v.1.0 tag in git to that point in the source.
7. Render to PDF and put the PDF into Scholarworks.
8. Add a pointer to the v.1.0 release to the README (http://trustedci.github.io/OSCRP/)
9. Update the source to make it clear it's now V.1.0+

**Comment by peisert** [comment]
Thanks, sounds good!

**Comment by akadams** [comment]
I've added links to both the README.md and OSCRP.md documents that point to our most recent release of OSCRP.html.  I've also used (well, moved) the date to show viewers what version of the document they are currently reading.  Note, I could *not* find a way to automatically add the GitHub Tag as the version in Markdown/Jekyll, so I settled for the date.  I created a new release in GitHub, tagging these changes as v1.1, including the new PDF of the document in the release.  I think we're good to go (sans the entries/PDF in Scholarworks).

**Comment by von** [comment]
We have a handle: http://hdl.handle.net/2022/21259

Note the OSCRP is not uploaded yet, this is just a placeholder for the moment.

**Comment by von** [comment]
I added the recommended handle to the document and cut a v1.2 release to include the recommended citation: https://github.com/trustedci/OSCRP/releases/tag/v1.2

I then added another commit indicating the document is now post 1.2

Yes, this approach means we hardcode the latest version into the document, but I think it's only clear way to let a reader know what version they are looking at.

Only thing left now is to get the PDF into scholarworks...

**Comment by von** [comment]
The PDF has been uploaded and the following citation is now good and in the document. 

> Peisert, Sean, Von Welch, Andrew Adams, RuthAnne Bevier, Michael Dopheide, Rich LeDuc, Pascal Meunier, Steve Schwab, and Karen Stocks. 2017. Open Science Cyber Risk Profile (OSCRP), Version 1.2. March 2017. http://hdl.handle.net/2022/21259
