### ISSUE TITLE
Given credit to those who presented to the WG in the document

### ISSUE THREAD

**Issue by von** [trustedci/OSCRP#6]
Make sure to acknowledge the views they presented were their own and not official statements.

**Comment by dopheide-esnet** [comment]
Be clear they were giving personal rather than project speakers and verify with the speakers that they want to be listed.

**Comment by von** [comment]
Ask them first to make sure it's OK.

In a new Acknowledgment section.

**Comment by von** [comment]
Actually, I suggest we leave out the projects and just list the names, e.g.:

> The working group thanks the following for presenting their thoughts on scientific project risks: Alice, Bob, Carol, etc.

I still suggest we ask them, but it seems much less sensitive without listing projects.
