### ISSUE TITLE
Verifying incident example highlights 

### ISSUE THREAD

**Issue by akadams** [trustedci/OSCRP#7]
First, the incident examples need to be identified in some way (even it it's just itemized), so we can reference them easier.  Second, the (currently) 3rd incident's assets that is highlighted is incorrect.  That is, _servers_ refer to server hardware purchased by the project, I believe this incident is referring to server (cluster) is owned by the institution.  Perhaps an argument to include institution's systems/hardware?

**Comment by von** [comment]
Second part is done.
First part is duplicated by #24.
