### ISSUE TITLE
Embargoed data example process

### ISSUE THREAD

**Issue by akadams** [trustedci/OSCRP#8]
The example process for our embargoed data asset needs to included specific System and/or Hardware assets, showing how the AoA are exposed/broadened/revealed? as more systems/hardware are involved in the concerns about an asset.  Likewise, the embargoed data asset diagram needs to reference other assets in its AoA (similar to the other data assets).

**Comment by dopheide-esnet** [comment]
Dop Todo:  Update embargoed data diagram and update example.
